name: Update heatmap

on:
  push:
    branches: [master, main]

jobs:
  heatmap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: tj-actions/puppeteer@v3.2
        with:
          node-version: 16
      - run: npm install

      - name: Generate heatmap.png
        run: node index.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Tino Schroeter
          author_email: tino.schroeter@gmail.com
          message: ":robot: generated new heatmap.png"
          add: "heatmap.png"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
